[Application Options]
alias=sats402-agent
color=#f7931a
listen=0.0.0.0:9735
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
tlsextraip=127.0.0.1
tlsextraip=0.0.0.0
tlsextradomain=localhost
tlsextradomain=lnd-agent
debuglevel=info
maxpendingchannels=20

[Bitcoin]
bitcoin.active=true
bitcoin.signet=true
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=bitcoind:38332
bitcoind.rpcuser=sats402
bitcoind.rpcpass=sats402
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333
